name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a2126913e45f8b363bca51af9fdb1913a5fca9557bf01c38f9502959ded7aa4"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
