name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8018632901dbf2246afeb40de706d3f7def66543a259b2f057f8e526f0712246"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
