name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "face9c35145e44cb427fd81823a44a7d7b89e30be193dab525f8cf98d8275e61"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
