name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "820428a5f9ff49d737c19a7ee6b0bb294ab619cbed74f48f995038635fbb1795"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
