name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65633bd0d93f9a8fd5b3d27f3ca44c923aa785e896864b6031bf41481fc33a71"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
