name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13a089b348e520f8b907b565ecdde127e78520c762d3c2fc391717755cf649e7"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
