name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bde2233065e436394c18bdafcfc3f7b445750b97df0f9028ca226a5bf095a8a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
