name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6b45f4fabddbdc7f373a9308da4cfb0c2efa091b090c5f94e5479aaa5175b56"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
