name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffc531f5c767372b62c43cdac17d4c41746770ab1bd1a038403c7b068965eda2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
