name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d8035a5a271bad0fa69ca87d016bdea694203439a53742ecf2454c8985635d2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
