name = "mias awesome modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "119c273dd44b0e08ff5b0bc9b8a355282406b4409e7cb3d8c05d87f834d5a746"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
